dist: bionic
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
cache: pip
install:
  - make install-dev
before_script:
  - make lint
script:
  - make test
after_success:
  - pip install codecov
  - codecov
